
version: '2.2'
services:
  es01:
    image: elasticsearch:8.4.3
    container_name: es01
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200 OK'
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elastic

  kibana:  
    image: kibana:8.4.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    healthcheck:
      test: curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'
      interval: 10s
      timeout: 10s
      retries: 120
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - elastic

networks:
  elastic:
    driver: bridge